# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.12.29'
  inputs:
    terraformVersion: 0.12.29

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : azurerm'
  inputs:
    backendServiceArm: 'Azure subscription 1 (ef797a3b-ebc6-4c45-a0f0-817c4447b0ef)'
    backendAzureRmResourceGroupName: azuredevopsresource
    backendAzureRmStorageAccountName: azurestorageudacity
    backendAzureRmContainerName: azurecontainer
    backendAzureRmKey: test.tfstate